/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddModal: typeof import('./resources/js/Pages/Booking/AddModal.vue')['default']
    AddRoomsModal: typeof import('./resources/js/Pages/Booking/AddRoomsModal.vue')['default']
    ApplicationLogo: typeof import('./resources/js/Components/ApplicationLogo.vue')['default']
    AuthenticatedLayout: typeof import('./resources/js/Layouts/AuthenticatedLayout.vue')['default']
    AvailableRoom: typeof import('./resources/js/Pages/Welcome/AvailableRoom.vue')['default']
    BookNowIndex: typeof import('./resources/js/Pages/Booking/BookNowIndex.vue')['default']
    Checkbox: typeof import('./resources/js/Components/Checkbox.vue')['default']
    ConfirmPassword: typeof import('./resources/js/Pages/Auth/ConfirmPassword.vue')['default']
    Coursel: typeof import('./resources/js/Pages/Welcome/Coursel.vue')['default']
    Curousel: typeof import('./resources/js/Pages/Welcome/Curousel.vue')['default']
    DangerButton: typeof import('./resources/js/Components/DangerButton.vue')['default']
    Dashboard: typeof import('./resources/js/Pages/Dashboard.vue')['default']
    DeleteUserForm: typeof import('./resources/js/Pages/Profile/Partials/DeleteUserForm.vue')['default']
    Description: typeof import('./resources/js/Pages/Welcome/Description.vue')['default']
    Dropdown: typeof import('./resources/js/Components/Dropdown.vue')['default']
    DropdownLink: typeof import('./resources/js/Components/DropdownLink.vue')['default']
    Edit: typeof import('./resources/js/Pages/Profile/Edit.vue')['default']
    Footer: typeof import('./resources/js/Pages/Welcome/Footer.vue')['default']
    ForgotPassword: typeof import('./resources/js/Pages/Auth/ForgotPassword.vue')['default']
    GuestLayout: typeof import('./resources/js/Layouts/GuestLayout.vue')['default']
    Headings: typeof import('./resources/js/Pages/Welcome/Headings.vue')['default']
    InputError: typeof import('./resources/js/Components/InputError.vue')['default']
    InputLabel: typeof import('./resources/js/Components/InputLabel.vue')['default']
    Login: typeof import('./resources/js/Pages/Auth/Login.vue')['default']
    Modal: typeof import('./resources/js/Components/Modal.vue')['default']
    NavLink: typeof import('./resources/js/Components/NavLink.vue')['default']
    PrimaryButton: typeof import('./resources/js/Components/PrimaryButton.vue')['default']
    Ratings: typeof import('./resources/js/Pages/Welcome/Ratings.vue')['default']
    Register: typeof import('./resources/js/Pages/Auth/Register.vue')['default']
    ResetPassword: typeof import('./resources/js/Pages/Auth/ResetPassword.vue')['default']
    ResponsiveNavLink: typeof import('./resources/js/Components/ResponsiveNavLink.vue')['default']
    SecondaryButton: typeof import('./resources/js/Components/SecondaryButton.vue')['default']
    TextInput: typeof import('./resources/js/Components/TextInput.vue')['default']
    UpdatePasswordForm: typeof import('./resources/js/Pages/Profile/Partials/UpdatePasswordForm.vue')['default']
    UpdateProfileInformationForm: typeof import('./resources/js/Pages/Profile/Partials/UpdateProfileInformationForm.vue')['default']
    VerifyEmail: typeof import('./resources/js/Pages/Auth/VerifyEmail.vue')['default']
    Welcome: typeof import('./resources/js/Pages/Welcome.vue')['default']
    WelcomeFooter: typeof import('./resources/js/Pages/Welcome/WelcomeFooter.vue')['default']
    WelcomeVideo: typeof import('./resources/js/Pages/Welcome/WelcomeVideo.vue')['default']
  }
}
